//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ipek
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public int kullaniciID { get; set; }
        public string kullaniciadi { get; set; }
        public string kullanicisifre { get; set; }
    }
}
